require_relative 'classes/user'
require_relative 'classes/question'
require_relative 'classes/question_follower'
require_relative 'classes/reply'
require_relative 'classes/question_like'
require_relative 'classes/tag'
